import cv2
imagen=cv2.imread("image.jpg",cv2.IMREAD_GRAYSCALE)
imagenfull=cv2.imread("image.jpg")
redimencionar=cv2.resize(imagenfull,(1000,400))
reverse=cv2.flip(imagen,10)
vertical=cv2.flip(imagen,-1)
rotar=cv2.rotate(imagen,cv2.ROTATE_90_COUNTERCLOCKWISE)
print(imagen)
print(imagen.shape)
#cv2.imshow("Gray image", imagen)
#cv2.imshow("XD",reverse+imagen)
#cv2.imshow("XD",vertical)
cv2.imshow("XD",rotar)
cv2.waitKey(0)